[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sondre Tveit Amundsen", email = "sondre.t.amundsen@himolde.no" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.143.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
